---
bosh:
  authentication: OAUTH
  host: 192.168.50.6
  stemcellOs: ubuntu-xenial
  stemcellVersion: latest
  username: admin
  vip_network: floating
catalog:
  services:
    - bindable: true
      bindings_retrievable: true
      dashboard:
        auth_endpoint: https://uaa.local/oauth
        url: https://osb-example.local/custom/v2/authentication
      dashboard_client:
        id: osb-example.local
        redirect_uri: https://osb-example.local/custom/v2/authentication
        secret: 59180F71-5830-4FE4-BD90-9EB8108DGB28
      description: Example Service - Simulating a database service
      id: 8653E6CE-D760-4B63-98B8-7D6361BF1EB4
      instances_retrievable: true
      metadata:
        displayName: osb-example
        documentationUrl: https://github.com/evoila/osb-docs
        longDescription: Managed, high performance, example service
        providerDisplayName: evoila
      name: osb-example
      plans:
        - connections: 4
          description: Deployment of a small example service to an existing shared instance.
          free: true
          id: 206DBCB2-9F04-4F29-8BE4-411309DD520C
          metadata:
            bullets:
              - 1 GB disk size
              - super-fast
              - awesome
            costs:
              - amount:
                  eur: 10.732
                unit: monthly per vm
              - amount:
                  eur: 10.54
                  usd: 21.125
                unit: weekly per call
            displayName: Small DB
          name: s
          platform: EXISTING_SERVICE
        - connections: 10
          description: Deployment of a medium example service to an existing shared instance.
          free: false
          id: 7A0FA2C0-F615-4498-97CE-CD45E477C46B
          name: m
          platform: EXISTING_SERVICE
        - connections: 50
          description: Deployment of a large example service to an existing shared instance.
          free: false
          id: 602917BA-A0FE-4B75-ACA5-6FEACE29EFF0
          name: l
          platform: EXISTING_SERVICE
        - connections: 100
          description: Deployment of an extra large example service to an existing shared instance.
          free: false
          id: A05E7CB2-34F6-4015-BE94-4CF577CE737F
          name: xl
          platform: EXISTING_SERVICE
    - bindable: true
      bindings_retrievable: true
      dashboard:
        auth_endpoint: https://uaa.local/oauth
        url: https://osb-example.local/v2/authentication
      dashboard_client:
        id: osb-example-second.local
        redirect_uri: https://osb-example.local/v2/authentication
        secret: 70292F82-7052-4FE4-BC90-9EB8108DFB28
      description: Second Example Service - Also simulating a database service
      id: 0764E7CE-D760-4B63-98B8-7D6361BF1EB4
      instances_retrievable: true
      metadata:
        displayName: osb-example-second
        documentationUrl: https://github.com/evoila/osb-docs
        longDescription: Managed, high performance, second example service
        providerDisplayName: evoila
      name: osb-example-second
      plans:
        - connections: 4
          description: Deployment of a small example service to an existing shared instance.
          free: true
          id: 306DBCB2-8F93-4F29-8BE4-411309DD520C
          name: s
          platform: EXISTING_SERVICE
        - connections: 50
          description: Deployment of a large example service to an existing shared instance.
          free: false
          id: 782917BA-A9FE-4B75-ACA5-6FEACE29EFF0
          name: l
          platform: EXISTING_SERVICE
config:
  sb:
    name: osb-example
    uri: https://osb-example.local
  site:
    postfix: ""
    url: local
endpoints:
  custom:
    - identifier: osb-backup-manager
      url: http://localhost:8081
    - identifier: osb-log-metric-backend
      url: http://localhost:8090
  default: https://localhost:8080
haproxy:
  auth:
    token: e4b1c55309fc2c250afbf5c9007fb03538ae52e5650b045ca506002b8963b966 # Change this example token with your own
  token: e4b1c55309fc2c250afbf5c9007fb03538ae52e5650b045ca506002b8963b966 # Change this example token with your own
  uri: http://localhost:8082/agents/6b18c493ab97f211186e0303/schemas?type=listen
login:
  password: basic-password
  role: USER
  username: basic-username
site:
  iaas:
    platform: bosh-lite
spring:
  credhub:
    bosh-director: bosh-1
    certificate:
      ca: |
        -----BEGIN CERTIFICATE-----
        ## Add certificate
        -----END CERTIFICATE-----
      certificate: |
        -----BEGIN CERTIFICATE-----
        ## Add certificate
        -----END CERTIFICATE-----
      private_key: |
        -----BEGIN RSA PRIVATE KEY-----
        ## Add certificate
        -----END RSA PRIVATE KEY-----
    oauth2:
      access-token-uri: https://192.168.50.6:8443/oauth/token
      client-id: credhub-admin
      #client-secret: # Add CredHub secret
      registration-id: credhub-client
    url: https://192.168.50.6:8844
  security:
    oauth2:
      client:
        registration:
          credhub-client:
            provider: uaa
            client-id: credhub-admin
            #client-secret: # Add CredHub secret
            authorization-grant-type: client_credentials
        provider:
          uaa:
            token-uri: https://192.168.50.6:8443/oauth/token
  data:
    mongodb:
      database: database
      host: 127.0.0.1
      password: password
      port: 27017
      username: username
  profiles: example
  rabbitmq:
    host: 127.0.0.1
    password: password
    port: 5672
    username: username
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
